cargo-features = ["panic-immediate-abort"]

[package]
name = "hello-world"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "immediate-abort"
